---
- hosts: localhost
  vars:
    sshcfg: '/etc/ansible/ssh.cfg'
    server: 'lib.s2.shareok.prod'
    src: '/srv/migrate/'
    dest: 'downloads/'
  tasks:
  - include: fetch.yml
- hosts: all
  tasks:
  - include: shareok.yml
