---
- hosts: localhost
  vars:
    sshcfg: '/etc/ansible/ssh.cfg'
    server: 'lib.s2.shareok.prod'
    src: '/srv/migrate/'
    dest: 'downloads/'
  tasks:
  - include: fetch.yml
- hosts: all
  sudo: yes
  tasks:
  - include: shareok.yml
  - name: Ensure packages that work well with local VMs are installed.
    yum: name=chrony state=latest
